CREATE EXTERNAL TABLE `findings_inspector`(
    `aws_account_id` string COMMENT 'from deserializer',
    `severity` string COMMENT 'from deserializer',
    `fix_available` string COMMENT 'from deserializer',
    `finding_type` string COMMENT 'from deserializer',
    `title` string COMMENT 'from deserializer',
    `description` string COMMENT 'from deserializer',
    `finding_arn` string COMMENT 'from deserializer',
    `first_seen` string COMMENT 'from deserializer',
    `last_seen` string COMMENT 'from deserializer',
    `last_updated` string COMMENT 'from deserializer',
    `resource_id` string COMMENT 'from deserializer',
    `container_image_tags` string COMMENT 'from deserializer',
    `region` string COMMENT 'from deserializer',
    `platform` string COMMENT 'from deserializer',
    `resource_tags` string COMMENT 'from deserializer',
    `affected_packages` string COMMENT 'from deserializer',
    `package_installed_version` string COMMENT 'from deserializer',
    `fixed_in_version` string COMMENT 'from deserializer',
    `package_remediation` string COMMENT 'from deserializer',
    `file_path` string COMMENT 'from deserializer',
    `network_paths` string COMMENT 'from deserializer',
    `age_days` string COMMENT 'from deserializer',
    `remediation` string COMMENT 'from deserializer',
    `inspector_score` string COMMENT 'from deserializer',
    `inspector_score_vector` string COMMENT 'from deserializer',
    `status` string COMMENT 'from deserializer',
    `vulnerability_id` string COMMENT 'from deserializer',
    `vendor` string COMMENT 'from deserializer',
    `vendor_severity` string COMMENT 'from deserializer',
    `vendor_advisory` string COMMENT 'from deserializer',
    `vendor_advisory_published` string COMMENT 'from deserializer',
    `nvd_cvss3_score` string COMMENT 'from deserializer',
    `nvd_cvss3_vector` string COMMENT 'from deserializer',
    `nvd_cvss2_score` string COMMENT 'from deserializer',
    `nvd_cvss2_vector` string COMMENT 'from deserializer',
    `vendor_cvss3_score` string COMMENT 'from deserializer',
    `vendor_cvss3_vector` string COMMENT 'from deserializer',
    `vendor_cvss2_score` string COMMENT 'from deserializer',
    `vendor_cvss2_vector` string COMMENT 'from deserializer',
    `resource_type` string COMMENT 'from deserializer',
    `ami` string COMMENT 'from deserializer',
    `resource_public_ipv4` string COMMENT 'from deserializer',
    `resource_private_ipv4` string COMMENT 'from deserializer',
    `resource_ipv6` string COMMENT 'from deserializer',
    `resource_vpc` string COMMENT 'from deserializer',
    `port_range` string COMMENT 'from deserializer',
    `epss_score` string COMMENT 'from deserializer',
    `exploit_available` string COMMENT 'from deserializer',
    `last_exploited_at` string COMMENT 'from deserializer',
    `lambda_layers` string COMMENT 'from deserializer',
    `lambda_package_type` string COMMENT 'from deserializer',
    `lambda_last_updated_at` string COMMENT 'from deserializer',
    `reference_urls` string COMMENT 'from deserializer',
    `detector_name` string COMMENT 'from deserializer',
    `package_manager` string COMMENT 'from deserializer'
)
PARTITIONED BY (`year` int, `month` int, `day` int)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat' LOCATION 's3://inspector-findings.eu-west-1.620992746856/' TBLPROPERTIES (
    'classification' = 'csv',
    'escapeChar' = '\\',
    'has_encrypted_data' = 'true',
    'quoteChar' = '\"',
    'separatorChar' = ',',
    'skip.header.line.count' = '1',
    'transient_lastDdlTime' = '1724165428'
)